-- Bravocado Database Schema
-- Run this in Supabase SQL Editor for fresh setup.

-- 1. Profiles table
create table profiles (
  id text primary key,
  received_count int default 0,
  remaining_daily int default 5
);

-- 2. Transactions table
create table transactions (
  id bigint generated by default as identity primary key,
  sender_id text,
  receiver_id text,
  count int default 1,
  icon_type text,
  message_text text,
  channel_id text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Give avocado function (transactional)
create or replace function give_avocado(
  sender_id_input text,
  receiver_id_input text,
  count int,
  message_text text,
  channel_id_input text
) returns void as $$
begin
  -- Auto-create profiles if not exists
  insert into profiles (id, remaining_daily) values (sender_id_input, 5) on conflict (id) do nothing;
  insert into profiles (id, received_count) values (receiver_id_input, 0) on conflict (id) do nothing;

  -- Update counters
  update profiles set remaining_daily = remaining_daily - count where id = sender_id_input;
  update profiles set received_count = received_count + count where id = receiver_id_input;

  -- Log transaction
  insert into transactions (sender_id, receiver_id, count, icon_type, message_text, channel_id)
  values (sender_id_input, receiver_id_input, count, 'avocado', message_text, channel_id_input);
end;
$$ language plpgsql;
